"""
Hint generation for the CoSER agent.

Generates a detailed, dimension-aware coaching brief (similar to Sotopia) after
a simulation scores below threshold. The hint is applied to ALL character agents
uniformly (one hint for the multi-character simulation).

Key differences from Sotopia:
- 4 dimensions: Storyline Consistency, Character Fidelity, Anthropomorphism,
  Storyline Quality (all 1-10, normalized to 0-100 in eval_result)
- Reference conversation (original book dialogue) is available and is included
  directly in the teacher prompt to guide storyline direction
- Hint covers what the simulation did vs. what the reference shows
"""

import asyncio
import logging
from agents.utils import call_openai, remove_think
from agents.coser.prompt import DIMENSIONS, DIMENSION_DETAILS, ENVIRONMENT, NSP, remove_inner_thoughts

logger = logging.getLogger(__name__)

# Brief rubric for teacher prompt header
_RUBRIC_BRIEF = {
    "Storyline Consistency": (
        "1-10 · Does the conversation follow the same narrative arc and key events as the reference?"
    ),
    "Character Fidelity":    "1-10 · Does each character speak, act, and react like their book counterpart?",
    "Anthropomorphism":      "1-10 · Do characters behave like real humans (not like AI assistants)?",
    "Storyline Quality":     "1-10 · Is the dialogue well-crafted, natural, and progressively engaging?",
}


def get_teacher_character_prompt(
        book_title: str,
        character: str,
        character_profile: str,
        background: str,
        scenario: str,
        motivation: str,
        wo_thought: bool,
        other_character_profiles: dict,
        hint: str,
) -> str:
    """Character system prompt augmented with per-turn coaching hints.

    The hint (generated by GPT-5.4-nano) contains turn-by-turn feedback
    comparing the student's previous attempt to the reference. The teacher
    uses this to generate an improved response.
    """
    from agents.coser.prompt import get_character_prompt

    base_prompt = get_character_prompt(
        book_title, character, character_profile, background, scenario, motivation,
        thoughtless=wo_thought, other_character_profiles=other_character_profiles,
    )
    base_prompt = base_prompt.strip('\n')
    base_prompt += '\n\nSpeak concisely as humans, instead of being verbose. Limit your response to 60 words.\n\nAlways respond in English.'

    rubric_lines = "\n".join(f"  • {dim}: {desc}" for dim, desc in _RUBRIC_BRIEF.items())

    # Annotate the character's own lines in the reference
    coaching_section = f"""

---
## Scene Guidance (private, only visible to you)

**IMPORTANT: You are playing ONLY the role of {character} [Your role]. Output ONLY your own lines — never write lines for other characters.**

**Evaluation criteria:**
{rubric_lines}

**Per-turn coaching** (follow these directions to improve
your performance when it is your turn to speak):
{hint}
---
Remember: you are {character}. Only output your own lines."""

    return base_prompt + coaching_section


def _build_hint_prompt(
        reference_str: str,
        student_conversation: str,
        circumstance: dict,
        involved_character_profiles: dict,
        eval_result: dict,
        parsed_judge: dict,
) -> str:
    """Build a scene direction prompt comparing student output to reference."""

    # Find the 2 weakest dimensions for targeted improvement notes
    scored_dims = sorted(
        [(d, eval_result.get(d, {}).get("score", 100)) for d in DIMENSIONS],
        key=lambda x: x[1],
    )
    key_improvement_lines = []
    for dim, score in scored_dims[:2]:
        judge_reasoning = ""
        if isinstance(parsed_judge, dict):
            dim_data = parsed_judge.get(dim, {})
            if isinstance(dim_data, dict):
                judge_reasoning = dim_data.get("reasoning", "")
        note = (
            judge_reasoning
            if judge_reasoning
            else f"score {score:.0f}/100 — needs improvement"
        )
        key_improvement_lines.append(f"- **{dim}**: {note}")
    key_improvements = (
        "\n".join(key_improvement_lines)
        if key_improvement_lines
        else "(not available)"
    )

    return f"""You are a dialogue coach helping characters \
improve their roleplay.

## Student's generated conversation (previous attempt)
{student_conversation}

## Reference conversation (original book dialogue)
{reference_str}

## Judge feedback on weakest dimensions
{key_improvements}

---

Write 2-4 sentences of high-level feedback comparing the
student's attempt to the reference. Focus on the biggest
gaps: which characters are off, what key story beats are
missing, and what tone or style changes would help most.
Name the specific characters that need improvement.

Output only the feedback, no preamble."""


async def generate_hint(
        circumstance: dict,
        involved_character_profiles: dict,
        eval_result: dict,
        parsed_judge: dict,
        student_conversation: str = "",
) -> str:
    """Generate a scene direction hint comparing student output to reference.

    Returns a markdown-formatted hint string, or empty string on failure.
    """
    from agents.utils import truncate_text, truncate_turns_for_reference
    reference = circumstance.get("dialogues", [])
    reference_clean = [
        m if m["character"] == ENVIRONMENT
        else {**m, "message": remove_inner_thoughts(m["message"])}
        for m in reference
    ]
    reference_clean = truncate_turns_for_reference(
        reference_clean, content_key="message",
    )
    reference_str = "\n\n".join(
        f"{m['character']}: {m['message']}".strip("\n")
        for m in reference_clean
    )
    reference_str = truncate_text(reference_str, 2000)

    prompt = _build_hint_prompt(
        reference_str=reference_str,
        student_conversation=student_conversation,
        circumstance=circumstance,
        involved_character_profiles=involved_character_profiles,
        eval_result=eval_result,
        parsed_judge=parsed_judge,
    )
    messages = [{"role": "system", "content": ""}, {"role": "user", "content": prompt}]

    hint_text = None
    try:
        async with asyncio.timeout(200):
            hint_text = await call_openai(messages, model='gpt-5.4-nano', reasoning_effort='low')
            if hint_text:
                hint_text = remove_think(hint_text).strip()
    except asyncio.TimeoutError:
        logger.warning("CoSER hint generation timed out")
    except Exception as e:
        logger.warning(f"CoSER hint generation failed: {e}")

    if not hint_text:
        return ""

    header = (
        "=== Scene Reflection Hints ===\n"
        "(Review these hints before replaying this scene"
        " to achieve a higher score)\n\n"
    )
    return header + hint_text